# Generated by Django 4.2.6 on 2023-11-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalumnos', '0003_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(default='', max_length=9),
        ),
    ]
